name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Download Gradle 7.4.2
      run: |
        curl -L https://services.gradle.org/distributions/gradle-7.4.2-bin.zip -o gradle.zip
        unzip -q gradle.zip
        export PATH=$PWD/gradle-7.4.2/bin:$PATH
        which gradle
        gradle --version
    
    - name: Generate Gradle Wrapper
      run: |
        export PATH=$PWD/gradle-7.4.2/bin:$PATH
        rm -rf .gradle gradle/wrapper
        gradle wrapper --gradle-version 7.4.2
    
    - name: Build with Gradle
      run: |
        rm -rf ~/.gradle
        chmod +x ./gradlew && ./gradlew build --no-daemon
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: IsTheApp-APK
        path: app/build/outputs/apk/
